[package]
name = "pr-butler"
version = "0.1.0"
authors = ["Aleksander DÅ‚ugopolski <aleksander.dlugopolski@logihub.pl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = ">= 0.9.22"
